linters:
  disable-all: true
  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't ignore some of the issues that golangci-lint considers okay.
  exclude-use-default: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unused
    - gofumpt
    - goimports
    - nolintlint
    - paralleltest
    - revive

    # - gofmt
    # - goimports
    # - nolintlint
    # - paralleltest
    # - revive
    # - staticcheck
